<a href="https://colab.research.google.com/github/Sounak-thegeek/Blog-Website/blob/master/FakeNewsClassifierUsingLSTM_and_Bi_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("saurabhshahane/fake-news-classification")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/saurabhshahane/fake-news-classification/77.archive...

100%|██████████| 92.1M/92.1M [00:03<00:00, 28.1MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/saurabhshahane/fake-news-classification/versions/77

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv(path+"/WELFake_Dataset.csv", on_bad_lines = 'skip', engine = 'python')

In [ ]:
df.head()

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,1,NaN,Did they post their votes for Hillary already?,1
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1

In [ ]:
df.shape

(72154, 4)

In [ ]:
df.isnull().sum()

Unnamed: 0      0
title         565
text           57
label          20
dtype: int64

In [ ]:
df = df.dropna()
df['label'] = pd.to_numeric(df['label'], errors='coerce')
df = df.dropna(subset=['label'])

In [ ]:
X = df.drop('label', axis = 1)

In [ ]:
y = df['label']

In [ ]:
y.value_counts()

label
1.0    36507
0.0    35028
Name: count, dtype: int64

In [ ]:
X.shape

(71535, 3)

In [ ]:
y.shape

(71535,)

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.20.0'

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
voc_size = 5000

In [ ]:
##One Hot Representation

In [ ]:
messages = X.copy()

In [ ]:
messages['title'][0]

'LAW ENFORCEMENT ON HIGH ALERT Following Threats Against Cops And Whites On 9-11By #BlackLivesMatter And #FYF911 Terrorists [VIDEO]'

In [ ]:
messages.reset_index(inplace=True)

In [ ]:
messages

,index,Unnamed: 0,title,text
0,0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...
1,2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ..."
2,3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...
3,4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will..."
4,5,5,About Time! Christian Group Sues Amazon and SP...,All we can say on this one is it s about time ...
...,...,...,...,...
71530,72149,72129,Russians steal research on Trump in hack of U....,WASHINGTON (Reuters) - Hackers believed to be ...
71531,72150,72130,WATCH: Giuliani Demands That Democrats Apolog...,"You know, because in fantasyland Republicans n..."
71532,72151,72131,Migrants Refuse To Leave Train At Refugee Camp...,Migrants Refuse To Leave Train At Refugee Camp...
71533,72152,72132,Trump tussle gives unpopular Mexican leader mu...,MEXICO CITY (Reuters) - Donald Trump’s combati...
71534,72153,72133,Goldman Sachs Endorses Hillary Clinton For Pre...,Goldman Sachs Endorses Hillary Clinton For Pre...

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
  review = re.sub('[^a-zA-Z0-9]', ' ', messages['title'][i])
  review = review.lower()
  review = review.split()

  review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)

In [ ]:
corpus

['law enforc high alert follow threat cop white 9 11bi blacklivesmatt fyf911 terrorist video',
 'unbeliev obama attorney gener say charlott rioter peac protest home state north carolina video',
 'bobbi jindal rais hindu use stori christian convers woo evangel potenti 2016 bid',
 'satan 2 russia unv imag terrifi new supernuk western world take notic',
 'time christian group sue amazon splc design hate group',
 'dr ben carson target ir never audit spoke nation prayer breakfast',
 'hous intel chair trump russia fake stori evid anyth video',
 'sport bar owner ban nfl game show true american sport like speak rural america video',
 'latest pipelin leak underscor danger dakota access pipelin',
 'gop senat smack punchabl alt right nazi internet',
 'may brexit offer would hurt cost eu citizen eu parliament',
 'schumer call trump appoint offici overse puerto rico relief',
 'watch hilari ad call question health age clinton crime famili boss',
 'chang expect espn polit agenda despit huge subscrib declin breitbart',
 'billionair odebrecht brazil scandal releas hous arrest',
 'british woman lose virgin asylum seek rapist way church',
 'u n seek humanitarian paus sanaa street battleground',
 'major liber rag reluctantli publish articl presid trump outstand accomplish explain success everyon laugh',
 'second judg say clinton email setup may bad faith',
 'america give grand piano hors',
 'hillari crime famili end day u',
 'sean spicer baffl report claim trump respons hire flynn video',
 'unholi allianc hillari clinton saudi sponsor support terror islamist extrem',
 'even trump best friend joe scarborough handl disqualifi kkk support video',
 'boom danish govern consid seiz migrant valuabl pay benefit',
 'suprem court hear appeal texa voter id case new york time',
 'islam state driven last stronghold northern iraq',
 'senat propos give state option keep afford care act new york time',
 'belong extraterrestri lineag',
 'zimbabw mugab appear public first time sinc coup',
 'credit suiss boss face revolt banker strategi shift new york time',
 'rob innoc 12 yr old student given cdc survey transgend gay oral sex',
 'schaeubl head german parliament unblock coalit talk',
 'u china summit trump press xi trade north korea progress cite',
 'clinton extend lead trump 7 point reuter ipso',
 'joe biden shock announc hell man video',
 'comment une petit fill russ de 4 an appri parler 7 langu',
 'embolden nra threaten new york time come video',
 'noam chomski goe donald trump clown video',
 '5 way media respond butthurt donald trump victori',
 'iran russia turkey agre enforc syria ceas fire explain new york time',
 'break obama pois exact reveng putin unpreced cyber attack allegedli expos hillari email campaign hillari',
 'trump say brexit great thing want quick trade deal uk',
 'sekulow expect whine testimoni comey need grow act like adult',
 'mayday carolina queen new york time',
 'illinoi hous pass 5 billion tax packag spend plan',
 'time warner death privaci',
 'architect built career resuscit new york landmark new york time',
 'american dream revisit',
 'fear iranian gener left iraqi kurdish oil field desert',
 'toler mosul social unravel feel perman new york time',
 'u patent review board becom conserv target',
 'trump interview four fed chair job decid two three week',
 'delingpol top physicist lead republican urg trump quit pari climat agreement',
 'intern back libyan forc attack daesh posit sirt',
 'obamacar wheel slowli fall social healthcar train billion wast',
 'msnbc dnc reach deal host democrat debat new hampshir',
 'georgetown professor instruct student resist trump presid breitbart',
 'u hous approv bill financi regul cost',
 'ron paul support trump gop pick neocon love hillari',
 'progress de blasio visit iowa deni run presid want visit iowa',
 'elijah cum made sure gop well awar hypocrit hole regard flint',
 'fbi director comey octob surpris derail hillari white hous bid',
 'man seem think help world war two',
 'gop lawmak trump stop act like fragil snowflak town hall protest',
 'trump extol corpor profit seek corpor tax cut',
 'michael moor owe 4 99',
 'philippin ferri capsiz 251 board four dead',
 'hillari dnc speech go follow money video georg soro make stun 25 million donat hillari dem',
 'donald trump indonesia aleppo wednesday even brief new york time',
 'death toll blast somalia capit mogadishu top 200',
 'donald trump return bash fake media',
 'idiot destroy trump hollywood star get exactli deserv',
 'great flood 8 king rule earth 241 200 year',
 'three arrest start massiv fire atlanta interst bridg',
 'collaps russia hack witch hunt end well congress america',
 'white hous voic concern senat sept 11 lawsuit bill',
 'arab spring washington brussel riyadh axi',
 'women knit pink pussyhat ralli trump inaugur',
 'unsilenc whistleblow expos un cultur corrupt',
 'cnn advertis job list full time fake news report',
 'snapchat discov take hard line mislead explicit imag new york time',
 'face obama launch new refugeeswelcom twitter campaign twitter',
 'u alli show support strike syria',
 'homophob lose damn mind request give elsa girlfriend hit twitter',
 'obama troll trump mean tweet late night tv',
 'anoth clinton casualti sister woman allegedli photo prove affair bill clinton question involv mysteri hous fire death',
 'challeng trump immigr order spread u state',
 'labour leader uk lawmak could lose seat cost cut plan',
 'corner everglad way life ebb new york time',
 'trump advis tpp dead move quickli bilater trade deal',
 'trevor noah compar texan excit open carri law gay pride parad celebr video',
 'lol democrat poster child stupid tell msnbc host parti stand besid hate trump video',
 'trump threaten comey via twitter autocrat move yet',
 'lithuania get minor govern junior partner leav',
 'boiler room ep 124 weather warfar cnn goblin pit',
 'colleg republican presid attack antifa like pack wolv',
 'beyonc doubl debut lemonad anoth race bait cop hate pro obama song sweet michael brown mama serena william',
 'one person shot portland anti trump protest cross bridg polic',
 'help immigr chobani founder draw threat new york time',
 'lol costco put hillari milk aisl book sign custom shout hillari prison ask membership refund video',
 'watch judg order punk wear polic lie shirt leav courtroom face contempt charg',
 'world see diminish america',
 'conserv messag dreamer scream presid hilari',
 'marketwatch leftist msm blatant anti trump bia may suicid',
 'comment facebook daughter day hoax sign time para kazanmak',
 'hate angri obama tri bash trump front canadian parliament real classi bo',
 'dod team survey us militari site potenti gitmo transfer lawmak vow fight',
 'way door harri reid give big f ck republican hand nevada hillari',
 'bombshel justic clarenc thoma accus sexual misconduct video',
 'german polic kill assail ax attack aboard train new york time',
 'austria spearhead balkan frontier defenc project',
 'cnn one voter make differ vote repeatedli',
 'comment 7 effect way balanc hormon natur eat way balanc hormon neilmd com',
 'nativ american tribe offer cash school stop use indian mascot 1 3 nativ american live poverti',
 'poll show exactli much american detest trump',
 'unhing nba coach white peopl especi need made uncomfort video',
 'new york citi budget boss state piggi bank',
 'long vote line could long term consequ new york time',
 'trump advisor tri pivot fishtail',
 'hillari land prison oval offic',
 'zimbabw mugab resign end four decad rule',
 'nuclear option speech trump render sullen democrat irrelev breitbart',
 'donald trump tax record show could avoid tax nearli two decad time found new york time',
 'factbox trump twitter juli 25 jeff session obamacar trade deal',
 'five state depart rule hillari violat video',
 'dalla ralli video trump let rip lame stream media karl rove',
 'california consid tighter lobbi rule 2016 elect near',
 '5 star mooch taxpay fund mom meryl streep travel africa discuss gender inequ',
 'homeschool educ altern rise',
 'mexico presidenti race roil leftist front runner embrac right wing parti',
 'atlant vp democrat news via internet left peopl overwhelm inform breitbart',
 'kentucki counti appeal feder rule strike right work law',
 'break courag feder judg deni obama request lift stay execut amnesti',
 'wikileak show georg soro control vote 16 state use smartmat vote machin',
 'macron call french food chain chang help farmer',
 'woodward clinton foundat corrupt',
 'sharia law grant muslim man permiss marri 8 year old video',
 'watch fox news host call presid obama weak declar war isi',
 'poll find voter parti unhappi candid new york time',
 'fox host goe soulless hillari clinton chelsea respons priceless tweet',
 'germani may need constitut chang allow strike back hacker',
 'understand clinton moment consid came 32 year ferraro new york time',
 'bolton threat trump middl east polici',
 'life migrant center germani rt talk volunt refuge hope fear',
 '5 key takeaway presid trump speech new york time',
 'clinton beat trump 9 point pennsylvania matter',
 'guatemalan man die fall wast grinder meat plant former worker claim hire 90 illeg alien includ 10 12 yr old kid',
 'brexit divorc first trade talk later e u tell u k new york time',
 'ingraham trump iest part obamacar reform miss new health care bill breitbart',
 'barack obama final arm export total doubl bush administr',
 'gloriou new pc nfl start next monday',
 'indian court acquit dentist coupl kill daughter',
 'former cia agent say obama work muslim brotherhood remov american power influenc includ militari forc islam land',
 'obama obliter gop threat kill suprem court hillari win',
 'pennsylvania republican push ban privat gun sale breitbart',
 'free care bless victim orlando nightclub attack new york time',
 'boiler room ep 113 cnn isi',
 'factbox trump twitter decemb 7 pearl harbor remembr day',
 'trump unyield hispan judg uproar',
 'chelsea handler hilari proposit donald trump larg hand tweet',
 'tuesday even brief donald trump golden state warrior hillari clinton new york time',
 'exclus trump say major major conflict north korea possibl seek diplomaci',
 'elect whistleblow doj cahoot dem 4 million dead voter roll trump right video',
 'updat 9 11 memori ban trigger colleg snowflak',
 'trump step attack bimbo tweet fox news debat',
 'expert claim n korea second missil test demonstr abil hit 3 major citi u mainland',
 'exclus cambodia say opposit parti could bar elect',
 'johnson amend trump vow destroy explain new york time',
 'daili show hasan minaj break charact admit scare famili video',
 'lionel shriver address cultur appropri roil writer festiv new york time',
 'republican insid take aim trump call penc drop',
 'trump u antitrust nomine say independ white hous',
 'watch thing get ugli canada self proclaim feminist prime minist elbow woman conserv parti hous common floor',
 'boati mcboatfac ii p brave ask public name new ferri',
 'lol liber ohio activist goe jail 13 count feloni voter fraud one year fals accus elect board voter fraud video',
 'donald trump alma mater told go f ck',
 'nanobot caus overwhelm depress far end',
 'messag left immigr disagre america first root',
 'hillari clinton suprem court abort rule victori women',
 'theresa may nation threat level remain sever terrorist attack highli like breitbart',
 'amerika toler univers educ exil trump voter american campus',
 'trump daughter ivanka join call argentina macri',
 'trump son forg ahead without father expand navig conflict new york time',
 'jack heart lucif templ dog',
 'saudi arabia face battl repatri asset corrupt crackdown',
 'place put hand togeth new york time',
 'unit resum newark delhi flight halt due poor air qualiti',
 'galleri hope sell kany west famou sculptur 4 million new york time',
 'rudi giuliani slam hillari refus endors one group make sick',
 'mistrial 2 ex offic albuquerqu kill mental ill man new york time',
 'twitter destroy trump ironi scream c mark hillari email',
 'russia warn close retali new u sanction bill ifax',
 'liber media scrub clip chuck todd say someth mean ted cruz video',
 'one hilari tweet perfectli sum irrelev cnn becom',
 '100 dead philippin mudslid flood offici',
 'court order nigeria pay 288 million 1967 war victim',
 'chri paul fast hand gruesom finger new york time',
 'japan discuss broad econ framework u bilater fta aso',
 '10 way america prepar world war 3',
 'famili arm robberi suspect outrag pizza hut employe shot kill son',
 'anti trump radic taunt trump support isi flag photo behead video',
 'wow atlanta gym owner ban cop make apolog polici sign video',
 'turkish presid return istanbul sign militari coup falter new york time',
 'comment sjw outrag leonardo dicaprio white rumi role unfound iranian explain ztech',
 'video hillari clinton twist approv sanctuari citi illeg alien',
 'break florida elect employe caught fake 1 000 stolen absente ballot massiv voter fraud scheme usapoliticsnow',
 'billionair donald trump presidenti campaign flat broke',
 'trump say strong europ import u',
 'report peopl leav new york metro area u breitbart',
 'obama rob fanni freddi billion dr ben carson shock discoveri hud could clue video',
 'attorney gener session defend repli russia contact',
 'syrian war report octob 28 2016 milit make die attempt break aleppo sieg',
 'clinton pantsuit inspir flashmob video',
 'tom ford move back us trump made feel nationalist breitbart',
 'u militari must accept transgend recruit jan 1 judg rule',
 'trump roger stone order court voter intimid tactic',
 'putin say trump hamper deliv elector promis',
 'trump hold seri meet assembl new administr',
 'tv viewership fall n f l premier leagu blip someth wors new york time',
 '3 remedi mediev europ heal common cold',
 'california governor sign epinephrin bill blast mylan',
 'break news clinton inform gag order hillari shake pantsuit',
 'trump flip flop complain obama deport mani peopl',
 'russia claim may kill isi leader al baghdadi',
 'black femal math whiz space race new york time',
 'presid trump issu warn john mccain senat tough speech',
 'appeal court judg explain donald trump immigr order legal breitbart',
 'trump endors romney niec ronna romney mcdaniel rnc chair',
 'hey simpleton got great news left go help identifi fake news video',
 'istanbul ataturk airport reopen jet crash turkish airlin ceo say',
 'hous take action block obama releas everi last guantanamo terrorist leav white hous',
 'anthoni weiner huma abedin separ latest sext scandal new york time',
 'hilari watch happen campu cop tri kick student trump campu build trump wall video',
 'watch sarah palin trump endors speech video',
 'break news trump admin announc massiv tax cut busi massiv tax reform video',
 'nasti like democrat salli kohn prove littl think women tweet',
 'love first leak former baywatch star pamela anderson becom regular visitor wikileak founder julian assang think quit sexi',
 'donald trump win presid histor victori',
 'north carolina hillari support brag facebook vote multipl time',
 'world war 3 come',
 'putin tell obama western media either stop talk final show kind proof',
 'watch lewi black hilari burn trump mock inaugur daili show',
 'promin russian journalist leav countri threat',
 'video show whale swim may chang everyth know bp oil spill video',
 'u led coalit say islam state syria convoy split two',
 'iraq vote ban american respons trump immigr order breitbart',
 'texa teen fatal shoot 5 day nra recommend gun safeti cours video',
 'hillari go prison oval offic video',
 'comment defici magnesium mani sign sunshin season sad magnesium activ health',
 'former prime minist elect presid struggl somalia new york time',
 'terribl week trump stick style substanc wisconsin',
 'liber past idiot',
 'benefit paleo diet',
 'calai jungl burn refuge tri storm way back',
 'obama immigr plan seem divid suprem court new york time',
 'jerri springer bannon want america basic christian white breitbart',
 'watch trump bi racial former girlfriend two year would never date racist',
 'u suprem court decid major case obama immigr plan',
 'watch chuck todd blister rnc chair trump tax return refus video',
 'gao examin panel foreign invest u strateg firm',
 'angri inspir democrat train new wave candid',
 'mr weiner',
 'india call rohingya refuge threat nation secur',
 'pope franci warn nation take refuge assimil',
 'u senat move jeff session toward confirm attorney gener',
 '1 million donat wound warrior project sale american sniper dvd',
 'former u attorney clear intel conspir frame trump video',
 'turkey say gulen network behind u case turkish trader',
 'break clinton chairman sister law lobbi clinton state depart earn six figur incom',
 'iceland pm call snap elect coalit parti quit breach trust',
 'battl bathroom loom larg north carolina governor race',
 'must read obama treason goe overdr',
 'pro clinton group launch devast nuclear war ad trump',
 'saudi king say kingdom made progress tackl terror',
 'trump take corpor tax rate could look much like obama new york time',
 'dispatch wolf countri sit cave watch spider spin',
 'turkey detain lawyer hunger strike teacher ahead trial',
 'taiwan presid visit u territori guam despit chines ire',
 'xi call concert effort resolv korean peninsula issu xinhua',
 'hillari pander black vote bust awkard fake laugh griev mom bring cheat bill video',
 'list 65 mainstream media journalist never trust wikileak bust media hack work hillari top advisor',
 'rememb pam offic real life actress jenna fischer got call twitter use bad inform bash trump tax bill',
 'maria sharapova suspend tenni two year new york time',
 'pinera win first round chile elect face runoff',
 'america elect hack miss link discov',
 'california governor sign legisl limit assault weapon new york time',
 'campaign presid trump hold els campaign ralli new york time',
 'un slam aleppo rebel amid accus poison ga attack',
 'music video russian die never surrend',
 'build wall hous vote fund trump wall partisan vote',
 'artist peter doig win case involv paint attribut new york time',
 'hawaii renew bid narrow trump travel ban',
 'protest target trump build massiv street ralli',
 'trump pull romney first debat say mention bill infidel unless hillari video',
 'hurrican irma like drop categori 4 upon landfal florida nhc',
 'latino loath trump drive voter movement swing elect',
 '',
 'white hous say congress reason wait nov elect take tpp',
 'u n envoy urg secur council visit myanmar bangladesh',
 'trump nomin hassett chair council econom advis',
 'obama list regret failur secur gun control still 1',
 'sen tim scott run small busi make author abort video',
 'trump execut order ethic commit ban lobbi execut branch employe',
 'secur cellphon',
 'pope urg trump show concern poor guid ethic valu',
 'sugar feed cancer cell may even creat',
 'public bullish toward stock see one highest 2 week jump histori',
 'state depart enough email record spokesman',
 'texa colleg student outrag tradit 9 11 memori flag display move could offend student',
 'nra admit alway lie obama confisc gun',
 'ny time sanctuari citi enough',
 'judg napolitano reckless hillari email could respons death cia fbi agent video',
 'episod 208 network sunday wire hesher funk oul patrick henningsen live iraq',
 'bust damag clinton foundat email yet friend bill',
 'tom hayden thing come around mideast',
 'watch trump declar one best presid histori histor low approv rate',
 'factbox five fact mike penc trump run mate pick',
 'unit state anxieti crime',
 'ohio state univers student say terrorist attack misunderstand caus racism video',
 'illeg invas continu nyc ramp give 1 million illeg vote right',
 'holland trump agre clarifi key issu includ middl east sourc',
 'watch chomski explain gop danger organ human histori',
 'trump son law obliter jewish famili defend trump anti semit tweet',
 'intersect time elitist exclusionari',
 'america take 37 027 refuge 5 month take refuge place list',

In [ ]:
onehot_repr=[one_hot(words, voc_size) for words in corpus]
onehot_repr

[[1414,
  4205,
  101,
  333,
  4007,
  3945,
  2195,
  3785,
  4333,
  1208,
  4706,
  1713,
  1277,
  4749],
 [1740,
  3134,
  4739,
  4289,
  2013,
  3233,
  172,
  562,
  2700,
  623,
  3098,
  545,
  1024,
  4749],
 [269, 4446, 2730, 3507, 113, 1217, 1855, 382, 784, 1513, 4701, 955, 600],
 [3966, 2215, 2220, 4349, 4159, 3556, 1072, 1340, 475, 3038, 200, 3913],
 [849, 1855, 4109, 3325, 4070, 1834, 1929, 766, 4109],
 [3235, 3745, 4322, 4126, 2692, 298, 3944, 627, 3892, 911, 4917],
 [4022, 2660, 1984, 1721, 2220, 2517, 1217, 897, 4015, 4749],
 [609,
  1628,
  535,
  3830,
  2859,
  1238,
  4714,
  4817,
  3540,
  609,
  3171,
  586,
  1589,
  3096,
  4749],
 [2969, 2123, 3491, 592, 2969, 4612, 3453, 2123],
 [4328, 4030, 3223, 97, 443, 1691, 4736, 2997],
 [1462, 1492, 1815, 3408, 2139, 1676, 1054, 1099, 1054, 4882],
 [4691, 4672, 1721, 631, 3805, 4673, 4468, 3686, 413],
 [4041, 1301, 942, 4672, 3531, 1474, 888, 4860, 1238, 3577, 2860],
 [1153, 4940, 3559, 4008, 1855, 2202, 4187, 3491, 3403, 4639],
 [1929, 3919, 2003, 2039, 3695, 4022, 3230],
 [3856, 1608, 3938, 1570, 4474, 4408, 806, 3107, 2068],
 [4964, 1826, 4408, 2161, 3196, 4618, 1650, 786],
 [687,
  4715,
  2136,
  164,
  2952,
  3696,
  1537,
  1721,
  4912,
  30,
  3912,
  2920,
  889,
  1725],
 [1691, 2453, 2013, 4860, 2901, 4225, 1462, 3655, 4294],
 [3096, 535, 4921, 754, 1882],
 [2950, 1238, 3577, 3660, 4497, 4964],
 [4362, 3896, 4340, 1057, 2256, 1721, 2340, 1280, 2259, 4749],
 [1812, 2529, 2950, 4860, 2447, 205, 750, 2559, 714, 975],
 [4934, 1721, 2446, 1193, 4334, 896, 350, 1793, 2098, 750, 4749],
 [3248, 3220, 1851, 1961, 4303, 286, 1028, 231, 4973],
 [4183, 1643, 1902, 1634, 1128, 3573, 3239, 651, 1072, 4503, 849],
 [1290, 3098, 3435, 3277, 3115, 439, 4268],
 [4030, 2083, 535, 3098, 4752, 3361, 2575, 2574, 3272, 1072, 4503, 849],
 [3120, 3447, 4166],
 [488, 4455, 3077, 4704, 801, 849, 4529, 4473],
 [3407, 2815, 2860, 4879, 3270, 4730, 2638, 4060, 1072, 4503, 849],
 [1079, 1032, 3441, 4989, 1890, 3852, 2559, 3476, 1530, 1437, 3601, 2047, 807],
 [533, 2357, 3055, 4882, 4708, 2018, 3939],
 [4964, 4727, 2535, 1721, 357, 3971, 3600, 545, 2574, 3850, 4984],
 [4860, 3637, 1507, 1721, 3256, 4240, 535, 752],
 [4334, 1143, 933, 3485, 376, 3763, 4749],
 [1245, 4414, 3772, 3014, 2870, 1244, 259, 1053, 1998, 97, 3256, 3338],
 [408, 465, 146, 1072, 4503, 849, 481, 4749],
 [1722, 595, 1417, 1218, 1721, 2059, 4749],
 [595, 3107, 972, 2808, 2697, 1218, 1721, 474],
 [2893, 2220, 1854, 2871, 4205, 3865, 3031, 300, 3912, 1072, 4503, 849],
 [2848,
  3134,
  3880,
  2501,
  2559,
  3735,
  3216,
  3428,
  3073,
  4862,
  68,
  2950,
  2901,
  4107,
  2950],
 [1721, 2013, 1492, 4895, 4586, 59, 1827, 3600, 2352, 1574],
 [1944, 4940, 35, 766, 4741, 4459, 308, 3272, 3171, 2819],
 [424, 1024, 1135, 1072, 4503, 849],
 [4250, 4022, 2576, 595, 1813, 737, 1099, 313, 4130],
 [849, 4261, 2546, 2395],
 [992, 1528, 3936, 3397, 1072, 4503, 4835, 1072, 4503, 849],
 [3540, 244, 1680],
 [2044, 467, 4289, 2363, 2120, 4589, 4185, 2010, 2825],
 [2533, 2416, 4217, 4173, 3608, 2989, 1072, 4503, 849],
 [4964, 1030, 1627, 227, 397, 4772, 4126],
 [1721, 3910, 2505, 826, 1984, 4061, 2590, 4787, 2636, 1120],
 [2835, 1250, 1103, 1507, 4768, 2733, 1721, 2148, 412, 3555, 3297],
 [1068, 4882, 564, 3811, 3073, 3653, 1783, 1891],
 [4072, 1595, 1352, 349, 4217, 779, 3151, 1813, 4874],
 [3471, 4422, 2424, 2352, 2652, 3113, 2803, 1072, 3631],
 [2102, 2462, 2966, 3852, 554, 1721, 1537, 4639],
 [4964, 4022, 3164, 83, 569, 1028, 1676],
 [1843, 3431, 750, 1721, 4328, 4349, 2976, 2276, 2950],
 [3850, 1244, 2691, 2537, 2480, 4039, 2145, 1537, 59, 2537, 2480],
 [391, 710, 3686, 3959, 4328, 1276, 1339, 1608, 2588, 1261, 3199],
 [3146, 1502, 4741, 2284, 107, 3085, 2950, 3785, 4022, 600],
 [3763, 4522, 3622, 1590, 3038, 4602, 4787],
 [4328, 3921, 1721, 3589, 3272, 3171, 4221, 3022, 97, 1875, 2700],
 [1721, 1241, 4371, 2632, 4408, 4371, 737, 1956],
 [1706, 3581, 3692, 259, 4354],
 [1342, 3620, 3331, 1970, 227, 2505, 1735],
 [2950,
  4422,
  2923,
  4438,
  4007,
  410,
  4749,
  2538,
  4874,
  4316,
  3864,
  1209,
  1145,
  3967,
  2950,
  1105],
 [1218, 1721, 1472, 2040, 1309, 4934, 2933, 1072, 4503, 849],
 [2546, 1075, 4371, 3632, 4399, 4383, 1250, 216],
 [1218, 1721, 4396, 2249, 2517, 972],
 [4996, 2147, 1721, 4131, 2655, 2173, 2003, 1891],
 [4895, 2907, 4956, 687, 1362, 2607, 2879, 216, 211],
 [2636, 3230, 3501, 3000, 300, 337, 176, 1959],
 [2847, 2220, 179, 99, 2672, 3660, 1276, 1783, 3096],
 [3785, 4022, 573, 1549, 4030, 461, 297, 4771, 83],
 [4652, 4513, 4746, 2464, 3608, 4373],
 [3517, 2427, 1354, 4044, 2299, 1721, 4629],
 [2727, 3089, 68, 3477, 2849, 927],
 [437, 531, 4061, 117, 3498, 849, 2517, 3819, 1057],
 [2871, 33, 200, 734, 3249, 1583, 3477, 4159, 1072, 4503, 849],
 [4879, 3134, 1824, 1072, 6, 240, 4107, 240],
 [4964, 2441, 4714, 750, 3582, 3865],
 [1806, 3938, 2731, 1573, 2772, 535, 4175, 381, 4473, 240],
 [3134, 2438, 1721, 4460, 3735, 3683, 361, 2840],
 [4686,
  4860,
  1683,
  3639,
  1608,
  4862,
  1020,
  2402,
  879,
  83,
  4860,
  3531,
  2956,
  1728,
  4022,
  300,
  2546],
 [2389, 1721, 131, 3638, 4902, 4964, 3098],
 [2583, 2491, 1574, 3921, 1069, 3938, 4643, 1676, 1956, 4130],
 [1812, 3971, 3107, 919, 645, 1072, 4503, 849],
 [1721, 354, 779, 1735, 2023, 4928, 1272, 3600, 2352],
 [106, 457, 1315, 415, 3162, 1652, 3767, 1414, 3601, 179, 105, 2829, 4749],
 [2988,
  3113,
  3661,
  434,
  2901,
  1098,
  3471,
  2652,
  866,
  2408,
  1829,
  766,
  1721,
  4749],
 [1721, 146, 4741, 1084, 240, 2579, 2023, 2257],
 [4560, 2173, 168, 1851, 1843, 2386, 1430],
 [3047, 4753, 2683, 4149, 65, 2860, 437, 1065, 2918],
 [314, 4768, 1537, 3073, 4153, 3171, 698, 2330],
 [1151,
  699,
  2095,
  2099,
  4686,
  4416,
  533,
  2195,
  766,
  2210,
  3134,
  4270,
  2165,
  1706,
  1948,
  661,
  3897,
  1171],
 [144, 825, 4503, 1414, 92, 1721, 2700, 213, 1959, 2438],
 [1590, 131, 1056, 2553, 1908, 3945, 1072, 4503, 849],
 [2988,
  2828,
  2809,
  2950,
  4166,
  678,
  3142,
  1612,
  2374,
  2697,
  2950,
  4803,
  3276,
  3554,
  4968,
  4749],
 [4041, 2453, 3638, 3824, 2681, 2438, 844, 3107, 1430, 3703, 4879, 3165, 1931],
 [3038, 323, 2310, 3096],
 [4772, 4672, 4381, 944, 1537, 1301],
 [2230, 98, 4782, 120, 92, 1721, 3918, 1462, 396],
 [1245, 967, 4661, 4497, 1608, 1612, 849, 4586, 3980],
 [766, 775, 3134, 860, 2249, 1721, 730, 3065, 4882, 303, 4129, 1815],
 [2492, 2772, 1530, 2173, 1998, 1859, 4701, 3004, 906, 3921, 2839, 4545],
 [3107, 4548, 1405, 694, 535, 28, 3696, 1241, 4768, 3200, 3455, 2950],
 [2544, 2788, 4616, 1157, 4934, 2035, 1943, 4749],
 [3055, 2438, 1987, 3525, 3292, 3073, 3191, 3151, 1072, 4503, 849],
 [4185, 378, 1152, 2517, 1394, 1967],
 [437, 144, 3573, 4316, 601, 3083, 577],
 [1245, 3256, 3668, 3107, 4443, 3332, 4762, 2371, 3107, 4443, 3332, 3762, 68],
 [4902,
  3540,
  3845,
  1815,
  1794,
  899,
  3589,
  113,
  3178,
  4894,
  3367,
  2919,
  4902,
  3540,
  2732,
  4270],
 [3508, 4714, 2003, 3611, 3540, 1868, 1721],
 [3800, 4481, 2342, 3785, 2412, 114, 4459, 3686, 4981, 4749],
 [1072, 4503, 384, 1603, 2860, 3098, 1520, 3138],
 [556, 3083, 3249, 1069, 556, 3849, 343, 1072, 4503, 849],
 [1721, 4984, 860, 320, 3776],
 [2950, 2734, 4803, 2178, 556],
 [488, 4455, 3917, 3660, 2505, 1565, 1362],
 [1908, 4752, 2923, 1721, 782, 1251, 3113, 3198, 4639],
 [1218,
  1721,
  737,
  1345,
  4714,
  1069,
  360,
  737,
  4588,
  4787,
  1565,
  849,
  494,
  1072,
  4503,
  849],
 [3157, 1721, 240, 3839, 1209, 4178, 484, 4072, 3600, 2352],
 [1910, 3098, 4086, 1362, 2950, 977, 4749],
 [158, 2299, 4749, 1721, 3129, 2694, 2308, 4307, 972, 2309, 3335],
 [866, 1961, 2583, 1836, 1362, 955, 1273, 238],
 [595, 2655, 3802, 3945, 4175, 2883, 2857, 1660, 2075, 3896, 1825, 3713, 4250],
 [3596, 1281, 4, 4682],
 [4340, 4752, 4416, 3197, 98, 730, 4629, 3239, 1691, 405, 866],
 [4553, 4861, 3113, 3819, 1084, 2997, 2363, 2412, 3825, 2060, 4639],
 [626, 1209, 1634, 2354, 1362, 3582, 1691, 3915, 1414],
 [2848, 86, 2354, 2453, 4039, 3134, 2772, 4746, 1979, 565, 3587],
 [579, 4714, 2538, 4874, 3750, 3083, 4354, 3098, 113, 4379, 3083, 489],
 [4571, 4672, 1981, 1807, 2517, 1153, 1590, 4650],
 [1076, 4860, 3303, 927],
 [4989, 1414, 3002, 1179, 3763, 4973, 4703, 4956, 211, 1890, 4749],
 [4041, 1807, 3819, 2652, 4672, 1537, 3134, 1049, 3105, 4602, 4209],
 [3508, 60, 3573, 866, 2894, 2460, 1072, 4503, 849],
 [1807, 2652, 1417, 253, 2950, 4860, 4758, 2340, 3953, 3735],
 [4804, 1462, 4459, 4286, 1153, 3172, 3582, 4882, 4776],
 [3436, 4860, 4245, 1961, 782, 2998, 211, 212, 1072, 4503, 849],
 [3003, 3945, 1721, 1987, 3155, 3874],
 [919, 286, 4085, 4804, 4832, 3939, 4245, 3919, 3521, 2044],
 [595, 1007, 958, 1537, 1721, 2923, 1072, 4503, 849],
 [4860, 1682, 1721, 4333, 4240, 2301, 1916],
 [671,
  3763,
  4903,
  349,
  4874,
  2428,
  3990,
  1970,
  4906,
  3048,
  2256,
  1280,
  771,
  1690,
  4922,
  313,
  4261,
  3441,
  4989,
  1890,
  2819],
 [1492,
  3612,
  801,
  3600,
  3939,
  908,
  4280,
  4964,
  1098,
  4964,
  2019,
  1072,
  4503,
  849],
 [1267, 1721, 301, 3628, 4072, 4145, 307, 1072, 1474, 2574, 83, 4639],
 [3931, 3134, 2442, 1547, 458, 4441, 699, 3254, 576],
 [3330, 1072, 1272, 2859, 3501, 35, 42],
 [3178, 1643, 4308, 2887, 2423, 1987, 4661],
 [4906,
  4900,
  4712,
  2013,
  3134,
  3915,
  1179,
  766,
  4690,
  3540,
  582,
  1270,
  313,
  1998,
  3811,
  1290,
  2734],
 [3134, 3558, 4328, 3945, 1987, 4183, 1643, 2950, 3135],
 [2301, 4768, 1301, 3830, 709, 4017, 321, 4639],
 [4188, 2574, 101, 4036, 1374, 3312, 3073, 1072, 4503, 849],
 [3047, 4753, 2683, 3628, 437, 4209],
 [3157, 1721, 240, 3403, 3256, 1949, 1508, 2015, 4497],
 [1721, 2801, 4071, 2453, 4874],
 [4758, 578, 1301, 545, 1218, 1721, 2352, 3200, 3735],
 [670, 4934, 2933, 1218, 1721, 118, 3098, 2300, 2950, 4860, 1072, 4503, 849],
 [776, 1721, 2013, 687, 687, 3946, 545, 2574, 3942, 4408, 3042],
 [1273, 3089, 2942, 3837, 1105, 259, 1145, 1735, 3573, 2687, 1721, 1691, 4749],
 [2690, 4333, 297, 3798, 3830, 1164, 314, 3022],
 [1721, 4466, 3073, 3112, 3735, 1807, 3819, 2803],
 [275,
  2256,
  1826,
  2574,
  1691,
  735,
  4663,
  4366,
  4146,
  4473,
  2919,
  687,
  384,
  4964,
  4401],
 [776, 2317, 2013, 3761, 866, 1069, 1628, 1273],
 [1795, 4248, 1721, 2839, 2147, 3912, 1072, 4503, 849],
 [3696, 4714, 1315, 2592, 2848, 3063, 152, 4810, 3577, 4749],
 [2976, 1651, 4203, 2849, 4329, 3197, 1692, 4292, 1072, 4503, 849],
 [4768, 1827, 200, 880, 1721, 4672, 1951, 1215],
 [1721, 4964, 3402, 160, 2013, 2405, 3785, 4022],
 [4041,
  4586,
  2173,
  3436,
  1981,
  340,
  4961,
  304,
  4270,
  3353,
  4689,
  1608,
  4772,
  866,
  4022,
  4760,
  1305],
 [1544, 964, 2750, 383, 24, 3276, 4704, 4631, 1072, 3620],
 [2988,
  4715,
  2720,
  162,
  1417,
  135,
  2788,
  4540,
  3551,
  3573,
  1266,
  144,
  211,
  1798,
  4934,
  1273,
  227,
  3573,
  1266,
  4749],
 [1218, 1721, 1079, 4002, 2570, 4438, 3696, 1241],
 [320, 2042, 3825, 762, 3547, 3660],
 [4672, 2363, 131, 923, 3096, 801, 1477],
 [2950, 4860, 4183, 1643, 3582, 1362, 474, 3517],
 [744, 1462, 3892, 3945, 4119, 3031, 2912, 1277, 3073, 4174, 3171, 4639],
 [3330, 2533, 1927, 1281, 4227, 1721, 3573, 3540, 2475],
 [1721, 4661, 3095, 777, 4672, 1414, 136],
 [1721, 3866, 1844, 4329, 3896, 3347, 4244, 2622, 3946, 1072, 4503, 849],
 [4802, 1444, 1665, 2841, 497],
 [2447, 2588, 4879, 385, 4375, 4088, 927, 1303],
 [279, 2809, 3200, 1344, 1072, 4503, 849],
 [4376, 3261, 3995, 1099, 4426, 4850, 2530, 3473, 3305, 4824],
 [4771, 3521, 4460, 1143, 1805, 2534, 4139, 259, 1145, 1072, 4503, 849],
 [2764, 653, 4949, 2950, 4079, 811, 144, 4109, 4316, 2915],
 [3949, 2215, 3451, 556, 1827, 1987, 1203, 2595, 3763, 1072, 4503, 849],
 [240, 2147, 1721, 4459, 944, 2011, 1780, 2950, 2901],
 [2220, 3641, 893, 3607, 1072, 4964, 2970, 83, 420],
 [4715, 972, 4277, 505, 534, 4063, 2013, 1920, 4460, 3803, 756, 4749],
 [144, 1301, 3735, 1667, 1439, 3198, 437, 397],
 [2426, 1735, 1342, 1983, 2907, 3805],
 [1643, 3638, 3512, 231, 3268, 1145, 3015, 4602, 4036],
 [3887, 3431, 1940, 3200, 3784, 3373, 1072, 4503, 849],
 [3417, 1825, 1614, 906, 2697, 4964, 1272, 4596, 1675],
 [4261, 3107, 3096, 1155, 3038, 4602, 2919],
 [3577, 1547, 49, 1910, 774, 4123, 2216, 3468, 4503, 1987, 3866],
 [92, 1721, 4087, 2234, 1721, 750, 4209, 919, 1020, 1484, 4749],
 [4863, 337, 686, 535, 3830, 2195, 4316, 3823, 3874, 1612, 4749],
 [4044, 1537, 4396, 4566, 1612, 1998, 4473, 3930, 1072, 4503, 849],
 [1245, 1909, 774, 2629, 4894, 3785, 4863, 1779, 2410, 467, 3912, 4757],
 [4749, 2950, 4860, 3868, 3164, 4324, 384, 1690, 4922],
 [2848,
  124,
  1273,
  3468,
  408,
  2517,
  3367,
  4460,
  1594,
  746,
  1574,
  3000,
  3573,
  1266,
  4949,
  97],
 [1929, 1218, 1721, 4752, 4107, 3805, 141],
 [1721, 2013, 861, 3481, 1803, 4964],
 [1057, 2412, 1430, 1072, 4503, 3107, 3941, 4964, 4639],
 [3134,
  1079,
  973,
  4400,
  1813,
  3235,
  3745,
  4322,
  933,
  766,
  1038,
  1069,
  395,
  4749],
 [4739, 4289, 484, 3360, 2623, 2220, 204],
 [584, 4602, 1057, 2284, 3580, 955, 779, 4316, 4903, 2843, 2848, 2040, 1234],
 [4860, 4493, 4984, 1067, 4749],
 [1901, 2537, 2023, 4882, 2173, 1721, 3686, 3608, 1496, 4639],
 [4964, 1998, 43, 3048, 1437, 1820, 1178, 3367, 2453, 1362],
 [1721, 4985, 1231, 3638, 1643, 3573, 2797, 198],
 [3735, 2013, 1721, 1390, 2174, 3963, 2227],
 [1721, 2775, 1623, 1365, 1000, 1072, 576],
 [2840,
  2829,
  349,
  1826,
  3696,
  1081,
  568,
  738,
  839,
  1920,
  458,
  1072,
  4503,
  849],
 [2919, 4272, 2695, 3481, 3290, 4760, 1209],
 [866, 2813, 1612, 150, 83, 4371, 2966],
 [2848, 3819, 4860, 2060, 2651, 3638, 2950, 45, 4493],
 [1721, 1583, 4456, 3955, 3134, 3552, 3742, 2412],
 [2220, 2256, 1462, 1987, 4209, 2491, 2900, 2091],
 [4797, 650, 564, 4909, 373, 4416, 1072, 4503, 849],
 [1537, 1721, 4113, 3641, 729, 3358, 4030, 4129, 2923],
 [1634, 1643, 2453, 3912, 1218, 1721, 131, 3638, 1076, 4639],
 [1721, 811, 1925, 3079, 3739, 1925, 4696, 3098, 1984],
 [2789, 3367, 2806, 4895, 3819, 2363, 4438, 1590, 3423, 2517, 3819, 4749],
 [4566, 3527, 2020, 2805, 417, 3222, 4044, 4758, 922, 2013],
 [4022, 200, 572, 1018, 3134, 3695, 3042, 3277, 4107, 1277, 1430, 3785, 4022],
 [3838, 3611, 1837, 1914, 4208, 2969, 185, 2039, 1072, 4503, 849],
 [1301,
  4041,
  454,
  4985,
  2195,
  860,
  1173,
  3852,
  1721,
  4985,
  4711,
  1721,
  1351,
  4749],
 [4041, 3305, 2778, 1721, 811, 2923, 4749],
 [2848, 3819, 1721, 1359, 3485, 3000, 737, 1956, 3726, 3000, 737, 4145, 4749],
 [2410, 3171, 3113, 4625, 1162, 2402, 3720, 3622, 3517, 3735],
 [2276,
  801,
  3491,
  4906,
  625,
  2655,
  3040,
  3699,
  397,
  3630,
  3982,
  579,
  2553,
  4945,
  603,
  3622,
  2148,
  1709],
 [1218, 1721, 3135, 1537, 70, 474],
 [545, 1024, 2950, 750, 3076, 967, 3083, 2350, 849],
 [3038, 4602, 2919, 481],
 [3735, 1098, 3134, 475, 972, 1636, 3589, 3939, 2442, 4714, 4362, 664],
 [4041, 1039, 4797, 1301, 80, 1721, 2424, 4629, 3696, 4714],
 [593, 3082, 3782, 1430, 1720, 3945],
 [4749, 4714, 3760, 2172, 1462, 1153, 2943, 3488, 1387, 4185, 3978, 4749],
 [4964, 1817, 2018, 2013, 1290, 3098, 3865, 4590, 937, 4787],
 [4268, 3083, 3830, 3540, 2340, 1721, 131, 3638, 4639],
 [1128, 4987, 4387, 77, 595, 4497, 465, 3822, 4017, 4230, 4863, 4749],
 [2950, 4438, 4803, 2178, 556, 4749],
 [1245, 1203, 1958, 3742, 1612, 4542, 4945, 4860, 1958, 2646, 1474],
 [4906, 4270, 3353, 1273, 1537, 4877, 3632, 1072, 4503, 849],
 [1970, 1120, 1721, 3975, 1907, 4209, 4237],
 [4715, 2636, 4996],
 [4973, 2534, 2769],
 [1838, 3432, 80, 3919, 860, 1247, 3107, 4882],
 [3134, 131, 4130, 4522, 1066, 4183, 1643, 1072, 4503, 849],
 [3437, 3856, 3807, 59, 3096, 4262, 1855, 3785, 4639],
 [4041, 1721, 3838, 3532, 4906, 381, 4787, 211, 3408, 298, 3400, 4906],
 [4964, 4183, 1643, 2590, 687, 651, 3134, 131, 4130],
 [4041, 534, 4063, 2652, 3098, 1984, 1721, 737, 4396, 4079, 4749],
 [4115, 885, 543, 1094, 3397, 4964, 828, 3067],
 [775, 4984, 3113, 3151, 1072, 3733, 2460],
 [3475, 3611],
 [100, 4672, 2033, 3919, 3945, 3892, 4767],
 [2412, 1153, 3641, 3892, 200, 3919, 4428],
 [4964, 4030, 2023, 4178, 484, 1443, 2886, 4739, 4289],
 [3367, 1145, 3967, 4918, 2300, 1967, 321, 3540, 1946, 2109],
 [4906, 4964, 4739, 1166, 2660, 3661, 4566, 1721, 4749],
 [1854, 2013, 752, 1603, 884, 4964, 651, 4044, 1330],
 [2848, 4860, 1169, 3639, 1414, 1836, 4860, 3098, 4086, 4496, 940, 951, 4669],
 [1424, 3495, 4672, 3805, 1273, 2018, 866, 2148, 1971, 1953],
 [385, 1551, 4765, 2352, 545, 1024, 2813, 4416],
 [43, 4400, 3134, 314, 1417, 3935],
 [2210, 4860, 4109, 1824, 4948, 1908, 4602, 942, 1721],
 [2447, 687, 2013, 4612, 3686, 3850, 615, 2559],
 [1721, 200, 4371, 737, 2348, 1069, 1018, 3611, 3171, 3134, 1072, 4503, 849],
 [3473, 3804, 1720, 4916, 1025, 4041, 2628, 2918],
 [1854, 2350, 431, 835, 3582, 4681, 4329, 1656],
 [687, 1537, 2537, 4964, 93, 306, 2202, 405, 4896],
 [3971, 4672, 1501, 3639, 1158, 151, 4861, 4113, 3483],
 [2950,
  816,
  4797,
  3083,
  3710,
  4124,
  2517,
  1725,
  4951,
  2883,
  4346,
  2464,
  83,
  4749],
 [117,
  3151,
  1377,
  972,
  3782,
  298,
  1953,
  579,
  3710,
  972,
  179,
  3915,
  2950,
  1250,
  4984],
 [4070,
  4743,
  556,
  303,
  919,
  1261,
  1108,
  1580,
  2806,
  4672,
  240,
  113,
  3655,
  2060,
  2249,
  1721,
  737,
  83],
 [2558, 4008, 3405, 1744, 4787, 211, 1072, 4503, 849],
 [1906, 3135, 801, 2180, 2283, 1273, 4879, 1458],
 [3096, 1273, 179, 307, 1909, 33],
 [866, 2813, 1612, 807, 2437, 4297, 1656, 1072, 4503, 849],
 [4107, 1537, 1721, 2775, 4733, 4107, 2299, 1072, 4503, 849],
 [3477, 4949, 2040, 3838, 581, 4934, 3718, 2524, 3073],
 [717, 4749, 3082, 4903, 298, 3311],
 [4711, 1351, 4022, 3083, 4175, 1721, 1351, 2506, 3083],
 [4779, 3232, 3028, 3135, 651, 2956, 2219, 2094, 1072, 4503, 849],
 [3142, 624, 600, 1297, 1721, 2075, 3830],
 [2700, 4126, 1721, 4711, 3000, 1650, 2299],
 [1721, 658, 1925, 801, 2803, 2013, 335, 83, 1002, 4025, 2950, 4749],
 [1846, 3753, 3171, 1215, 4241, 259, 4750, 4555, 124, 4307],
 [4187, 3877, 1721, 1687, 3573, 1904, 3138, 1273],
 [],
 [3785, 4022, 2013, 1783, 4772, 2070, 1641, 1273, 200, 779],
 [4964, 1826, 817, 2733, 4767, 3028, 2537, 2641, 1109],
 [1721, 2610, 532, 1984, 3028, 3837, 354],
 [3134, 117, 3922, 3912, 4767, 4017, 3750, 4283, 3367],
 [2409, 2349, 3229, 2145, 1174, 3726, 4316, 3038, 3582, 4749],
 [1721, 565, 3638, 1263, 4936, 3830, 1836, 565, 915, 3468],
 [4767, 429],
 [2412, 2733, 1721, 4714, 1549, 3473, 1627, 1263, 4187],
 [4672, 552, 2149, 1281, 1462, 4934, 2720],
 [4704, 3743, 1443, 629, 323, 144, 697, 2215, 1120, 1233, 4369],
 [3098, 4086, 649, 2901, 1345, 416],
 [1128,
  314,
  3852,
  774,
  3188,
  4333,
  297,
  3798,
  919,
  1247,
  2023,
  1069,
  544,
  3852],
 [465, 152, 4047, 844, 3134, 4934, 4017],
 [303, 849, 4324, 384, 649],
 [2453, 4198, 4297, 2950, 2901, 1069, 2340, 2546, 4900, 3146, 4712, 4749],
 [1008, 3490, 1603, 1832, 1652, 4562, 2829, 1486, 950, 1942, 2732, 4268],
 [3710, 3021, 4860, 3303, 2901, 2257, 1193, 83],
 [1901, 334, 4586, 481, 3013, 4315],
 [4041, 1721, 3105, 144, 2446, 1537, 4369, 70, 2714, 3164, 2348],
 [3157, 1910, 3085, 3088, 1951, 1721, 2145, 2570, 4349],
 [4376, 3098, 986, 1238],
 [2720, 3098, 1927, 3852, 2013, 1277, 3073, 4829, 2042, 4364, 4749],
 [1690, 483, 1337, 3796, 4969, 535, 3367, 1145, 1690, 3083, 1691],
 [4190, 1721, 2871, 1674, 1007, 4113, 313, 1987, 3155, 3598],
 [4041, 595, 3912, 4328, 2969, 3615, 560, 4369],
 [1721, 3866, 1414, 3558, 3771, 3577, 3360, 1721, 92, 1770, 3735],
 [1444, 849, 3664, 4192],
 [3096, 200, 3816, 2947, 3919, 595, 4278, 200, 3919, 279, 117],
 [4589, 2491, 1819, 2242, 2120, 4882, 3083, 4690, 4205, 2813, 4589, 972],
 [2459, 3040, 431, 2700, 4989, 2105, 200, 1169, 3796, 4639],
 [1721, 4126, 131, 4964, 4572, 4652, 1018, 3698],
 [3580, 4, 113, 919, 2040, 4695, 1006, 1540],
 [3887, 3154, 486, 955, 1273, 1933, 3488, 3546, 4460, 4749],
 [4166, 3120, 1019, 2071, 516, 801, 1362, 3038],
 [437, 1764, 2534, 2013, 2295, 3305, 4234, 2956, 2013, 1132, 4685, 807],
 [715, 1574, 586, 1547, 152, 1191, 179, 3077, 11, 4123, 4701],
 [3248, 2453, 3665, 333, 1072, 42, 122, 2720, 3134, 4749],

In [ ]:
corpus[1]

'unbeliev obama attorney gener say charlott rioter peac protest home state north carolina video'

In [ ]:
onehot_repr[1]

[1740,
 3134,
 4739,
 4289,
 2013,
 3233,
 172,
 562,
 2700,
 623,
 3098,
 545,
 1024,
 4749]

In [ ]:
##Embedding Representation

In [ ]:
sent_length = max(len(sen) for sen in corpus)

In [ ]:
sent_length

299

In [ ]:
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen = sent_length)

In [ ]:
print(embedded_docs)

[[   0    0    0 ... 1713 1277 4749]
 [   0    0    0 ...  545 1024 4749]
 [   0    0    0 ... 4701  955  600]
 ...
 [   0    0    0 ... 3919 4635 1802]
 [   0    0    0 ... 4459 4503 1547]
 [   0    0    0 ... 2950 4860 1537]]

In [ ]:
embedded_docs[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 1740,
       3134, 4739, 4289, 2013, 3233,  172,  562, 2700,  623, 3098,  545,
       1024, 4749], dtype=int32)

In [ ]:
from tensorflow.keras.layers import Dropout
embedding_vector_features = 40
model = Sequential()
model.add(Embedding(voc_size, embedding_vector_features, input_length = sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1, activation = 'sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics =['accuracy'])
print(model.summary())

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None

In [ ]:
len(embedded_docs), y.shape

(71535, (71535,))

In [ ]:
import numpy as np
X_final = np.array(embedded_docs)
y_final = np.array(y)

In [ ]:
X_final.shape, y_final.shape

((71535, 299), (71535,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [ ]:
##Model training

In [ ]:
y_train = y_train.astype(int)
y_test = y_test.astype(int)
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs = 10, batch_size=32)

Epoch 1/10
1498/1498 ━━━━━━━━━━━━━━━━━━━━ 45s 30ms/step - accuracy: 0.9354 - loss: 0.1589 - val_accuracy: 0.8902 - val_loss: 0.2893
Epoch 2/10
1498/1498 ━━━━━━━━━━━━━━━━━━━━ 45s 30ms/step - accuracy: 0.9451 - loss: 0.1349 - val_accuracy: 0.8885 - val_loss: 0.3314
Epoch 3/10
1498/1498 ━━━━━━━━━━━━━━━━━━━━ 83s 31ms/step - accuracy: 0.9511 - loss: 0.1214 - val_accuracy: 0.8910 - val_loss: 0.3328
Epoch 4/10
1498/1498 ━━━━━━━━━━━━━━━━━━━━ 81s 30ms/step - accuracy: 0.9559 - loss: 0.1120 - val_accuracy: 0.8912 - val_loss: 0.3434
Epoch 5/10
1498/1498 ━━━━━━━━━━━━━━━━━━━━ 44s 30ms/step - accuracy: 0.9608 - loss: 0.1006 - val_accuracy: 0.8914 - val_loss: 0.3877
Epoch 6/10
1498/1498 ━━━━━━━━━━━━━━━━━━━━ 45s 30ms/step - accuracy: 0.9620 - loss: 0.0945 - val_accuracy: 0.8905 - val_loss: 0.3617
Epoch 7/10
1498/1498 ━━━━━━━━━━━━━━━━━━━━ 44s 29ms/step - accuracy: 0.9662 - loss: 0.0854 - val_accuracy: 0.8928 - val_loss: 0.4181
Epoch 8/10
1498/1498 ━━━━━━━━━━━━━━━━━━━━ 45s 30ms/step - accuracy: 0.9685 - loss: 0.0792 - val_accuracy: 0.8904 - val_loss: 0.4328
Epoch 9/10
1498/1498 ━━━━━━━━━━━━━━━━━━━━ 47s 31ms/step - accuracy: 0.9706 - loss: 0.0756 - val_accuracy: 0.8901 - val_loss: 0.4196
Epoch 10/10
1498/1498 ━━━━━━━━━━━━━━━━━━━━ 81s 30ms/step - accuracy: 0.9729 - loss: 0.0693 - val_accuracy: 0.8906 - val_loss: 0.4329

In [ ]:
##Performance metrics and accuracy

In [ ]:
y_pred = model.predict(X_test)

738/738 ━━━━━━━━━━━━━━━━━━━━ 11s 15ms/step

In [ ]:
X_test

array([[   0,    0,    0, ..., 4109, 1316, 1057],
       [   0,    0,    0, ..., 1876, 4629, 3282],
       [   0,    0,    0, ..., 1466, 4903, 1921],
       ...,
       [   0,    0,    0, ..., 3082,   55, 3735],
       [   0,    0,    0, ..., 3485,  955, 1273],
       [   0,    0,    0, ..., 3096, 3460,  866]], dtype=int32)

In [ ]:
X_test.shape

(23607, 299)

In [ ]:
type(y_pred)

numpy.ndarray

In [ ]:
y_pred.shape

(23607, 1)

In [ ]:
y_pred = np.where(y_pred > 0.5, 1, 0)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test, y_pred)

array([[10417,  1218],
       [ 1400, 10572]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8891006904731648

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.90      0.89     11635
           1       0.90      0.88      0.89     11972

    accuracy                           0.89     23607
   macro avg       0.89      0.89      0.89     23607
weighted avg       0.89      0.89      0.89     23607

In [ ]:
##Bi-directional LSTM

In [ ]:
from tensorflow.keras.layers import Dropout, Bidirectional
embedding_vector_features = 40
model = Sequential()
model.add(Embedding(voc_size, embedding_vector_features, input_length = sent_length))
model.add(Dropout(0.3))
model.add(Bidirectional(LSTM(100)))
model.add(Dropout(0.3))
model.add(Dense(1, activation = 'sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics =['accuracy'])
print(model.summary())

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_9 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_10 (Dropout)            │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None

In [ ]:
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs = 10, batch_size=64)

Epoch 1/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 28s 32ms/step - accuracy: 0.8512 - loss: 0.3288 - val_accuracy: 0.8903 - val_loss: 0.2605
Epoch 2/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 24s 31ms/step - accuracy: 0.9032 - loss: 0.2325 - val_accuracy: 0.8929 - val_loss: 0.2561
Epoch 3/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 23s 31ms/step - accuracy: 0.9167 - loss: 0.2051 - val_accuracy: 0.8941 - val_loss: 0.2577
Epoch 4/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 23s 31ms/step - accuracy: 0.9239 - loss: 0.1864 - val_accuracy: 0.8943 - val_loss: 0.2614
Epoch 5/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 42s 33ms/step - accuracy: 0.9313 - loss: 0.1696 - val_accuracy: 0.8921 - val_loss: 0.2743
Epoch 6/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 24s 32ms/step - accuracy: 0.9381 - loss: 0.1544 - val_accuracy: 0.8938 - val_loss: 0.2919
Epoch 7/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 24s 32ms/step - accuracy: 0.9421 - loss: 0.1413 - val_accuracy: 0.8912 - val_loss: 0.3085
Epoch 8/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 24s 32ms/step - accuracy: 0.9471 - loss: 0.1302 - val_accuracy: 0.8898 - val_loss: 0.3111
Epoch 9/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 24s 32ms/step - accuracy: 0.9515 - loss: 0.1204 - val_accuracy: 0.8915 - val_loss: 0.3283
Epoch 10/10
749/749 ━━━━━━━━━━━━━━━━━━━━ 24s 32ms/step - accuracy: 0.9569 - loss: 0.1090 - val_accuracy: 0.8889 - val_loss: 0.3499

In [ ]:
y_pred = model.predict(X_test)

738/738 ━━━━━━━━━━━━━━━━━━━━ 8s 10ms/step

In [ ]:
y_pred = np.where(y_pred >= 0.5, 1, 0)

In [ ]:
confusion_matrix(y_test, y_pred)

array([[10296,  1339],
       [ 1284, 10688]])

In [ ]:
accuracy_score(y_test, y_pred)

0.8888888888888888

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      0.88      0.89     11635
           1       0.89      0.89      0.89     11972

    accuracy                           0.89     23607
   macro avg       0.89      0.89      0.89     23607
weighted avg       0.89      0.89      0.89     23607